### ISSUE TITLE
Error after compiling (Loading offsets.Please run this...)

### ISSUE THREAD

**Issue by Jobine23** [gmastergreatee/OneshotsGlowHack#4]
I built the project with success. But after launching the software it says:
Loading offsets.Please run this file with Admin-priviledges for it to work correctly
Searching for the running game, csgo.exe...

I tried to run csgo as admin, and also, the .exe .

Here's the build logs:

`1>------ Début de la régénération globale : Projet : OneshotsGlowHack, Configuration : Debug x64 ------
1>Glow.cpp
1>d:\workspace\9\oneshotsglowhack-oneshotgh-final\oneshotsglowhack\hprocess.h(83): warning C4311: 'cast de type' : troncation de pointeur de 'BYTE *' à 'DWORD'
1>d:\workspace\9\oneshotsglowhack-oneshotgh-final\oneshotsglowhack\hprocess.h(83): warning C4302: 'cast de type' : troncation de 'BYTE *' à 'DWORD'
1>d:\workspace\9\oneshotsglowhack-oneshotgh-final\oneshotsglowhack\glow.cpp(32): warning C4312: 'cast de type' : la conversion de 'unsigned long' en 'PBYTE *' d'une taille supérieure
1>d:\workspace\9\oneshotsglowhack-oneshotgh-final\oneshotsglowhack\glow.cpp(33): warning C4312: 'cast de type' : la conversion de 'unsigned long' en 'PBYTE *' d'une taille supérieure
1>d:\workspace\9\oneshotsglowhack-oneshotgh-final\oneshotsglowhack\glow.cpp(34): warning C4312: 'cast de type' : la conversion de 'unsigned long' en 'PBYTE *' d'une taille supérieure
1>d:\workspace\9\oneshotsglowhack-oneshotgh-final\oneshotsglowhack\glow.cpp(39): warning C4312: 'cast de type' : la conversion de 'DWORD' en 'PBYTE *' d'une taille supérieure
1>d:\workspace\9\oneshotsglowhack-oneshotgh-final\oneshotsglowhack\glow.cpp(41): warning C4312: 'cast de type' : la conversion de 'DWORD' en 'PBYTE *' d'une taille supérieure
1>d:\workspace\9\oneshotsglowhack-oneshotgh-final\oneshotsglowhack\glow.cpp(42): warning C4312: 'cast de type' : la conversion de 'DWORD' en 'PBYTE *' d'une taille supérieure
1>d:\workspace\9\oneshotsglowhack-oneshotgh-final\oneshotsglowhack\glow.cpp(43): warning C4312: 'cast de type' : la conversion de 'DWORD' en 'PBYTE *' d'une taille supérieure
1>d:\workspace\9\oneshotsglowhack-oneshotgh-final\oneshotsglowhack\glow.cpp(44): warning C4312: 'cast de type' : la conversion de 'DWORD' en 'PBYTE *' d'une taille supérieure
1>d:\workspace\9\oneshotsglowhack-oneshotgh-final\oneshotsglowhack\glow.cpp(46): warning C4312: 'cast de type' : la conversion de 'unsigned long' en 'PBYTE *' d'une taille supérieure
1>d:\workspace\9\oneshotsglowhack-oneshotgh-final\oneshotsglowhack\glow.cpp(47): warning C4312: 'cast de type' : la conversion de 'unsigned long' en 'PBYTE *' d'une taille supérieure
1>d:\workspace\9\oneshotsglowhack-oneshotgh-final\oneshotsglowhack\glow.cpp(52): warning C4312: 'cast de type' : la conversion de 'DWORD' en 'PBYTE *' d'une taille supérieure
1>OneshotsGlowHack.cpp
1>d:\workspace\9\oneshotsglowhack-oneshotgh-final\oneshotsglowhack\hprocess.h(83): warning C4311: 'cast de type' : troncation de pointeur de 'BYTE *' à 'DWORD'
1>d:\workspace\9\oneshotsglowhack-oneshotgh-final\oneshotsglowhack\hprocess.h(83): warning C4302: 'cast de type' : troncation de 'BYTE *' à 'DWORD'
1>d:\workspace\9\oneshotsglowhack-oneshotgh-final\oneshotsglowhack\oneshotsglowhack.cpp(132): warning C4267: 'initialisation' : conversion de 'size_t' en 'int', perte possible de données
1>d:\workspace\9\oneshotsglowhack-oneshotgh-final\oneshotsglowhack\oneshotsglowhack.cpp(139): warning C4267: 'initialisation' : conversion de 'size_t' en 'int', perte possible de données
1>d:\workspace\9\oneshotsglowhack-oneshotgh-final\oneshotsglowhack\oneshotsglowhack.cpp(153): warning C4267: 'initialisation' : conversion de 'size_t' en 'int', perte possible de données
1>Génération de code en cours...
1>OneshotsGlowHack.vcxproj -> D:\Workspace\9\OneshotsGlowHack-OneshotGH-Final\x64\Debug\OneshotsGlowHack.exe
1>Génération du projet "OneshotsGlowHack.vcxproj" terminée.
========== Régénération globale : 1 a réussi, 0 a échoué, 0 a été ignoré ==========
`

**Comment by gmastergreatee** [comment]
Sorry for the late reply, Been a bit busy the past 2 weeks.

The current exe file requires the file/s created by HazeDumper for obtaining the correct offsets.
Also you would need to put the files created by HazeDumper in the same folder as the "Hack"'s exe

To know how to use hazeDumper, please read [#readme](https://github.com/gmastergreatee/OneshotsGlowHack/blob/OneshotGH-Final/README.md#steps-to-update-the-hack-yourself)

If you still have problems after following the above steps, please notify.

**Comment by w3bn00b** [comment]
try to compile on x86 release
